investio/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path('', views.home, name='home'),
]

investio/investio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('register.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('django.contrib.auth.urls')),
]
#TODO check on production
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investio/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('investment/<int:id_>/', views.investment_detail_view, name='investment-detail-view'),
    path('add_investment/', views.add_investment, name='add_investment'),
    path('investments/', views.user_investments, name='user_investments'),
    path('edit/<int:id>/', views.edit_investment, name='edit_investment')
]

investio/register/urls.py
from django.urls import path
from . import views

app_name = "register"
urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

investio/templates/base.html
{% include 'header.html' %}

<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock %}
<script src="https://kit.fontawesome.com/5f267684f0.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
{% include 'footer.html' %}
</html>

investio/templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Invest.io
          </h6>
          <p>
            Twój partner w znalezieniu dobrej inwestycji
          </p>
        </div>
        <!-- Grid column -->



        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Przydatne linki
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Kontakt</h6>
          <p><i class="fas fa-home me-3"></i> Sosnowiec 41-200, Pusta 62</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            investio@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 48 516 154 328</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">InvestIO.pl</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

investio/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

investio/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top navbar-margin">
    <a style="font-size:2rem; padding:0;"class="navbar-brand" href="{% url 'main:home' %}">Invest<span style="color:#efab0a;">.io</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item px-2">
                <a class="nav-link" href="{% url 'main:home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link" href="{% url 'main:about' %}">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item px-2">
                <button type="button" class="btn btn-add-investment"><a href="{% url 'main:add_investment' %}">+ Add Investment</a></button>
            </li>
            {% else %}
            <li class="nav-item px-2">
                <button type="button" class="btn btn-add-investment"><a style="color:black;" href="/login">+ Add Investment</a></button>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            <div class="btn-group dropleft">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <img style="width: 20px" src="{% static 'images/user_default.png' %}" alt="user default photo">
                        <!--User icons created by Smashicons - Flaticon-->
                        {{user.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'dashboard:home' %}">Dashboard</a>
                        <a class="dropdown-item" href="{% url 'main:user_investments' %}">Your investments</a>
                        <a class="dropdown-item" href="{% url 'register:profile' %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/logout">Logout</a>
                    </div>
                </li>
            </div>
            {% else %}
            <li class="nav-item my-2 my-lg-0 mr-auto">
                <a class="nav-link" href="/login">Login</a>
            </li>
            {% endif %}
        </ul>


    </div>
</nav>